services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vetcare
    ports: ["5432:5432"]
    volumes: [ "db_data:/var/lib/postgresql/data" ]

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.test
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]
    depends_on: [ "db" ]

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports: ["1025:1025", "8025:8025"]

volumes:
  db_data:
